# Generated by Django 4.2.1 on 2023-05-10 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('background_image', models.ImageField(upload_to='hackathon_backgrounds/')),
                ('hackathon_image', models.ImageField(upload_to='hackathon_images/')),
                ('sumbission_type', models.CharField(choices=[('image', 'Image'), ('file', 'File'), ('link', 'Link')], max_length=10)),
                ('end_datetime', models.DateTimeField()),
                ('reward_prize', models.PositiveIntegerField()),
                ('start_datetime', models.DateTimeField()),
                ('organizer', models.ManyToManyField(related_name='organized_hackathons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
