# Generated by Django 4.2.1 on 2023-05-12 05:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackathon', '0002_hackathon_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='participants',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
