# Generated by Django 4.2.1 on 2023-05-12 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_alter_hackathon_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackathon',
            old_name='sumbission_type',
            new_name='submission_type',
        ),
    ]
